// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DataRecordProto.proto

package net.icircuit.bucketdb.models.proto;

public final class DataRecordProto {
  private DataRecordProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface DataRecordOrBuilder extends
      // @@protoc_insertion_point(interface_extends:kvstorageengine.DataRecord)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string rKey = 1;</code>
     * @return The rKey.
     */
    java.lang.String getRKey();
    /**
     * <code>string rKey = 1;</code>
     * @return The bytes for rKey.
     */
    com.google.protobuf.ByteString
        getRKeyBytes();

    /**
     * <code>string rValue = 2;</code>
     * @return The rValue.
     */
    java.lang.String getRValue();
    /**
     * <code>string rValue = 2;</code>
     * @return The bytes for rValue.
     */
    com.google.protobuf.ByteString
        getRValueBytes();

    /**
     * <code>int64 ttl = 3;</code>
     * @return The ttl.
     */
    long getTtl();

    /**
     * <code>int64 timestamp = 4;</code>
     * @return The timestamp.
     */
    long getTimestamp();
  }
  /**
   * Protobuf type {@code kvstorageengine.DataRecord}
   */
  public  static final class DataRecord extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:kvstorageengine.DataRecord)
      DataRecordOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use DataRecord.newBuilder() to construct.
    private DataRecord(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private DataRecord() {
      rKey_ = "";
      rValue_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new DataRecord();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private DataRecord(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              rKey_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              rValue_ = s;
              break;
            }
            case 24: {

              ttl_ = input.readInt64();
              break;
            }
            case 32: {

              timestamp_ = input.readInt64();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return net.icircuit.bucketdb.models.proto.DataRecordProto.internal_static_kvstorageengine_DataRecord_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return net.icircuit.bucketdb.models.proto.DataRecordProto.internal_static_kvstorageengine_DataRecord_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              net.icircuit.bucketdb.models.proto.DataRecordProto.DataRecord.class, net.icircuit.bucketdb.models.proto.DataRecordProto.DataRecord.Builder.class);
    }

    public static final int RKEY_FIELD_NUMBER = 1;
    private volatile java.lang.Object rKey_;
    /**
     * <code>string rKey = 1;</code>
     * @return The rKey.
     */
    public java.lang.String getRKey() {
      java.lang.Object ref = rKey_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        rKey_ = s;
        return s;
      }
    }
    /**
     * <code>string rKey = 1;</code>
     * @return The bytes for rKey.
     */
    public com.google.protobuf.ByteString
        getRKeyBytes() {
      java.lang.Object ref = rKey_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        rKey_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int RVALUE_FIELD_NUMBER = 2;
    private volatile java.lang.Object rValue_;
    /**
     * <code>string rValue = 2;</code>
     * @return The rValue.
     */
    public java.lang.String getRValue() {
      java.lang.Object ref = rValue_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        rValue_ = s;
        return s;
      }
    }
    /**
     * <code>string rValue = 2;</code>
     * @return The bytes for rValue.
     */
    public com.google.protobuf.ByteString
        getRValueBytes() {
      java.lang.Object ref = rValue_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        rValue_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TTL_FIELD_NUMBER = 3;
    private long ttl_;
    /**
     * <code>int64 ttl = 3;</code>
     * @return The ttl.
     */
    public long getTtl() {
      return ttl_;
    }

    public static final int TIMESTAMP_FIELD_NUMBER = 4;
    private long timestamp_;
    /**
     * <code>int64 timestamp = 4;</code>
     * @return The timestamp.
     */
    public long getTimestamp() {
      return timestamp_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getRKeyBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, rKey_);
      }
      if (!getRValueBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, rValue_);
      }
      if (ttl_ != 0L) {
        output.writeInt64(3, ttl_);
      }
      if (timestamp_ != 0L) {
        output.writeInt64(4, timestamp_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getRKeyBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, rKey_);
      }
      if (!getRValueBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, rValue_);
      }
      if (ttl_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, ttl_);
      }
      if (timestamp_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, timestamp_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof net.icircuit.bucketdb.models.proto.DataRecordProto.DataRecord)) {
        return super.equals(obj);
      }
      net.icircuit.bucketdb.models.proto.DataRecordProto.DataRecord other = (net.icircuit.bucketdb.models.proto.DataRecordProto.DataRecord) obj;

      if (!getRKey()
          .equals(other.getRKey())) return false;
      if (!getRValue()
          .equals(other.getRValue())) return false;
      if (getTtl()
          != other.getTtl()) return false;
      if (getTimestamp()
          != other.getTimestamp()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + RKEY_FIELD_NUMBER;
      hash = (53 * hash) + getRKey().hashCode();
      hash = (37 * hash) + RVALUE_FIELD_NUMBER;
      hash = (53 * hash) + getRValue().hashCode();
      hash = (37 * hash) + TTL_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTtl());
      hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTimestamp());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static net.icircuit.bucketdb.models.proto.DataRecordProto.DataRecord parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.icircuit.bucketdb.models.proto.DataRecordProto.DataRecord parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.icircuit.bucketdb.models.proto.DataRecordProto.DataRecord parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.icircuit.bucketdb.models.proto.DataRecordProto.DataRecord parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.icircuit.bucketdb.models.proto.DataRecordProto.DataRecord parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.icircuit.bucketdb.models.proto.DataRecordProto.DataRecord parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.icircuit.bucketdb.models.proto.DataRecordProto.DataRecord parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static net.icircuit.bucketdb.models.proto.DataRecordProto.DataRecord parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static net.icircuit.bucketdb.models.proto.DataRecordProto.DataRecord parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static net.icircuit.bucketdb.models.proto.DataRecordProto.DataRecord parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static net.icircuit.bucketdb.models.proto.DataRecordProto.DataRecord parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static net.icircuit.bucketdb.models.proto.DataRecordProto.DataRecord parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(net.icircuit.bucketdb.models.proto.DataRecordProto.DataRecord prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code kvstorageengine.DataRecord}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:kvstorageengine.DataRecord)
        net.icircuit.bucketdb.models.proto.DataRecordProto.DataRecordOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return net.icircuit.bucketdb.models.proto.DataRecordProto.internal_static_kvstorageengine_DataRecord_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return net.icircuit.bucketdb.models.proto.DataRecordProto.internal_static_kvstorageengine_DataRecord_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                net.icircuit.bucketdb.models.proto.DataRecordProto.DataRecord.class, net.icircuit.bucketdb.models.proto.DataRecordProto.DataRecord.Builder.class);
      }

      // Construct using net.icircuit.bucketdb.models.proto.DataRecordProto.DataRecord.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        rKey_ = "";

        rValue_ = "";

        ttl_ = 0L;

        timestamp_ = 0L;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return net.icircuit.bucketdb.models.proto.DataRecordProto.internal_static_kvstorageengine_DataRecord_descriptor;
      }

      @java.lang.Override
      public net.icircuit.bucketdb.models.proto.DataRecordProto.DataRecord getDefaultInstanceForType() {
        return net.icircuit.bucketdb.models.proto.DataRecordProto.DataRecord.getDefaultInstance();
      }

      @java.lang.Override
      public net.icircuit.bucketdb.models.proto.DataRecordProto.DataRecord build() {
        net.icircuit.bucketdb.models.proto.DataRecordProto.DataRecord result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public net.icircuit.bucketdb.models.proto.DataRecordProto.DataRecord buildPartial() {
        net.icircuit.bucketdb.models.proto.DataRecordProto.DataRecord result = new net.icircuit.bucketdb.models.proto.DataRecordProto.DataRecord(this);
        result.rKey_ = rKey_;
        result.rValue_ = rValue_;
        result.ttl_ = ttl_;
        result.timestamp_ = timestamp_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof net.icircuit.bucketdb.models.proto.DataRecordProto.DataRecord) {
          return mergeFrom((net.icircuit.bucketdb.models.proto.DataRecordProto.DataRecord)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(net.icircuit.bucketdb.models.proto.DataRecordProto.DataRecord other) {
        if (other == net.icircuit.bucketdb.models.proto.DataRecordProto.DataRecord.getDefaultInstance()) return this;
        if (!other.getRKey().isEmpty()) {
          rKey_ = other.rKey_;
          onChanged();
        }
        if (!other.getRValue().isEmpty()) {
          rValue_ = other.rValue_;
          onChanged();
        }
        if (other.getTtl() != 0L) {
          setTtl(other.getTtl());
        }
        if (other.getTimestamp() != 0L) {
          setTimestamp(other.getTimestamp());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        net.icircuit.bucketdb.models.proto.DataRecordProto.DataRecord parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (net.icircuit.bucketdb.models.proto.DataRecordProto.DataRecord) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object rKey_ = "";
      /**
       * <code>string rKey = 1;</code>
       * @return The rKey.
       */
      public java.lang.String getRKey() {
        java.lang.Object ref = rKey_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          rKey_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string rKey = 1;</code>
       * @return The bytes for rKey.
       */
      public com.google.protobuf.ByteString
          getRKeyBytes() {
        java.lang.Object ref = rKey_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          rKey_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string rKey = 1;</code>
       * @param value The rKey to set.
       * @return This builder for chaining.
       */
      public Builder setRKey(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        rKey_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string rKey = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearRKey() {
        
        rKey_ = getDefaultInstance().getRKey();
        onChanged();
        return this;
      }
      /**
       * <code>string rKey = 1;</code>
       * @param value The bytes for rKey to set.
       * @return This builder for chaining.
       */
      public Builder setRKeyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        rKey_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object rValue_ = "";
      /**
       * <code>string rValue = 2;</code>
       * @return The rValue.
       */
      public java.lang.String getRValue() {
        java.lang.Object ref = rValue_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          rValue_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string rValue = 2;</code>
       * @return The bytes for rValue.
       */
      public com.google.protobuf.ByteString
          getRValueBytes() {
        java.lang.Object ref = rValue_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          rValue_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string rValue = 2;</code>
       * @param value The rValue to set.
       * @return This builder for chaining.
       */
      public Builder setRValue(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        rValue_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string rValue = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearRValue() {
        
        rValue_ = getDefaultInstance().getRValue();
        onChanged();
        return this;
      }
      /**
       * <code>string rValue = 2;</code>
       * @param value The bytes for rValue to set.
       * @return This builder for chaining.
       */
      public Builder setRValueBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        rValue_ = value;
        onChanged();
        return this;
      }

      private long ttl_ ;
      /**
       * <code>int64 ttl = 3;</code>
       * @return The ttl.
       */
      public long getTtl() {
        return ttl_;
      }
      /**
       * <code>int64 ttl = 3;</code>
       * @param value The ttl to set.
       * @return This builder for chaining.
       */
      public Builder setTtl(long value) {
        
        ttl_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 ttl = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearTtl() {
        
        ttl_ = 0L;
        onChanged();
        return this;
      }

      private long timestamp_ ;
      /**
       * <code>int64 timestamp = 4;</code>
       * @return The timestamp.
       */
      public long getTimestamp() {
        return timestamp_;
      }
      /**
       * <code>int64 timestamp = 4;</code>
       * @param value The timestamp to set.
       * @return This builder for chaining.
       */
      public Builder setTimestamp(long value) {
        
        timestamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 timestamp = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearTimestamp() {
        
        timestamp_ = 0L;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:kvstorageengine.DataRecord)
    }

    // @@protoc_insertion_point(class_scope:kvstorageengine.DataRecord)
    private static final net.icircuit.bucketdb.models.proto.DataRecordProto.DataRecord DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new net.icircuit.bucketdb.models.proto.DataRecordProto.DataRecord();
    }

    public static net.icircuit.bucketdb.models.proto.DataRecordProto.DataRecord getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<DataRecord>
        PARSER = new com.google.protobuf.AbstractParser<DataRecord>() {
      @java.lang.Override
      public DataRecord parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new DataRecord(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<DataRecord> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<DataRecord> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public net.icircuit.bucketdb.models.proto.DataRecordProto.DataRecord getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_kvstorageengine_DataRecord_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_kvstorageengine_DataRecord_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025DataRecordProto.proto\022\017kvstorageengine" +
      "\"J\n\nDataRecord\022\014\n\004rKey\030\001 \001(\t\022\016\n\006rValue\030\002" +
      " \001(\t\022\013\n\003ttl\030\003 \001(\003\022\021\n\ttimestamp\030\004 \001(\003B5\n\"" +
      "net.icircuit.bucketdb.models.protoB\017Data" +
      "RecordProtob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_kvstorageengine_DataRecord_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_kvstorageengine_DataRecord_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_kvstorageengine_DataRecord_descriptor,
        new java.lang.String[] { "RKey", "RValue", "Ttl", "Timestamp", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
