// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: FileFooterProto.proto

package net.icircuit.bucketdb.models.proto;

public final class FileFooterProto {
  private FileFooterProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface FileFooterOrBuilder extends
      // @@protoc_insertion_point(interface_extends:kvstorageengine.FileFooter)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 dibOffset = 1;</code>
     * @return The dibOffset.
     */
    long getDibOffset();

    /**
     * <code>int64 dibLength = 2;</code>
     * @return The dibLength.
     */
    long getDibLength();
  }
  /**
   * Protobuf type {@code kvstorageengine.FileFooter}
   */
  public  static final class FileFooter extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:kvstorageengine.FileFooter)
      FileFooterOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use FileFooter.newBuilder() to construct.
    private FileFooter(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private FileFooter() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new FileFooter();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private FileFooter(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              dibOffset_ = input.readInt64();
              break;
            }
            case 16: {

              dibLength_ = input.readInt64();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return net.icircuit.bucketdb.models.proto.FileFooterProto.internal_static_kvstorageengine_FileFooter_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return net.icircuit.bucketdb.models.proto.FileFooterProto.internal_static_kvstorageengine_FileFooter_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              net.icircuit.bucketdb.models.proto.FileFooterProto.FileFooter.class, net.icircuit.bucketdb.models.proto.FileFooterProto.FileFooter.Builder.class);
    }

    public static final int DIBOFFSET_FIELD_NUMBER = 1;
    private long dibOffset_;
    /**
     * <code>int64 dibOffset = 1;</code>
     * @return The dibOffset.
     */
    public long getDibOffset() {
      return dibOffset_;
    }

    public static final int DIBLENGTH_FIELD_NUMBER = 2;
    private long dibLength_;
    /**
     * <code>int64 dibLength = 2;</code>
     * @return The dibLength.
     */
    public long getDibLength() {
      return dibLength_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (dibOffset_ != 0L) {
        output.writeInt64(1, dibOffset_);
      }
      if (dibLength_ != 0L) {
        output.writeInt64(2, dibLength_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (dibOffset_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, dibOffset_);
      }
      if (dibLength_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, dibLength_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof net.icircuit.bucketdb.models.proto.FileFooterProto.FileFooter)) {
        return super.equals(obj);
      }
      net.icircuit.bucketdb.models.proto.FileFooterProto.FileFooter other = (net.icircuit.bucketdb.models.proto.FileFooterProto.FileFooter) obj;

      if (getDibOffset()
          != other.getDibOffset()) return false;
      if (getDibLength()
          != other.getDibLength()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + DIBOFFSET_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getDibOffset());
      hash = (37 * hash) + DIBLENGTH_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getDibLength());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static net.icircuit.bucketdb.models.proto.FileFooterProto.FileFooter parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.icircuit.bucketdb.models.proto.FileFooterProto.FileFooter parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.icircuit.bucketdb.models.proto.FileFooterProto.FileFooter parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.icircuit.bucketdb.models.proto.FileFooterProto.FileFooter parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.icircuit.bucketdb.models.proto.FileFooterProto.FileFooter parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.icircuit.bucketdb.models.proto.FileFooterProto.FileFooter parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.icircuit.bucketdb.models.proto.FileFooterProto.FileFooter parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static net.icircuit.bucketdb.models.proto.FileFooterProto.FileFooter parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static net.icircuit.bucketdb.models.proto.FileFooterProto.FileFooter parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static net.icircuit.bucketdb.models.proto.FileFooterProto.FileFooter parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static net.icircuit.bucketdb.models.proto.FileFooterProto.FileFooter parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static net.icircuit.bucketdb.models.proto.FileFooterProto.FileFooter parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(net.icircuit.bucketdb.models.proto.FileFooterProto.FileFooter prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code kvstorageengine.FileFooter}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:kvstorageengine.FileFooter)
        net.icircuit.bucketdb.models.proto.FileFooterProto.FileFooterOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return net.icircuit.bucketdb.models.proto.FileFooterProto.internal_static_kvstorageengine_FileFooter_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return net.icircuit.bucketdb.models.proto.FileFooterProto.internal_static_kvstorageengine_FileFooter_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                net.icircuit.bucketdb.models.proto.FileFooterProto.FileFooter.class, net.icircuit.bucketdb.models.proto.FileFooterProto.FileFooter.Builder.class);
      }

      // Construct using net.icircuit.bucketdb.models.proto.FileFooterProto.FileFooter.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        dibOffset_ = 0L;

        dibLength_ = 0L;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return net.icircuit.bucketdb.models.proto.FileFooterProto.internal_static_kvstorageengine_FileFooter_descriptor;
      }

      @java.lang.Override
      public net.icircuit.bucketdb.models.proto.FileFooterProto.FileFooter getDefaultInstanceForType() {
        return net.icircuit.bucketdb.models.proto.FileFooterProto.FileFooter.getDefaultInstance();
      }

      @java.lang.Override
      public net.icircuit.bucketdb.models.proto.FileFooterProto.FileFooter build() {
        net.icircuit.bucketdb.models.proto.FileFooterProto.FileFooter result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public net.icircuit.bucketdb.models.proto.FileFooterProto.FileFooter buildPartial() {
        net.icircuit.bucketdb.models.proto.FileFooterProto.FileFooter result = new net.icircuit.bucketdb.models.proto.FileFooterProto.FileFooter(this);
        result.dibOffset_ = dibOffset_;
        result.dibLength_ = dibLength_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof net.icircuit.bucketdb.models.proto.FileFooterProto.FileFooter) {
          return mergeFrom((net.icircuit.bucketdb.models.proto.FileFooterProto.FileFooter)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(net.icircuit.bucketdb.models.proto.FileFooterProto.FileFooter other) {
        if (other == net.icircuit.bucketdb.models.proto.FileFooterProto.FileFooter.getDefaultInstance()) return this;
        if (other.getDibOffset() != 0L) {
          setDibOffset(other.getDibOffset());
        }
        if (other.getDibLength() != 0L) {
          setDibLength(other.getDibLength());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        net.icircuit.bucketdb.models.proto.FileFooterProto.FileFooter parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (net.icircuit.bucketdb.models.proto.FileFooterProto.FileFooter) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long dibOffset_ ;
      /**
       * <code>int64 dibOffset = 1;</code>
       * @return The dibOffset.
       */
      public long getDibOffset() {
        return dibOffset_;
      }
      /**
       * <code>int64 dibOffset = 1;</code>
       * @param value The dibOffset to set.
       * @return This builder for chaining.
       */
      public Builder setDibOffset(long value) {
        
        dibOffset_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 dibOffset = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearDibOffset() {
        
        dibOffset_ = 0L;
        onChanged();
        return this;
      }

      private long dibLength_ ;
      /**
       * <code>int64 dibLength = 2;</code>
       * @return The dibLength.
       */
      public long getDibLength() {
        return dibLength_;
      }
      /**
       * <code>int64 dibLength = 2;</code>
       * @param value The dibLength to set.
       * @return This builder for chaining.
       */
      public Builder setDibLength(long value) {
        
        dibLength_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 dibLength = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearDibLength() {
        
        dibLength_ = 0L;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:kvstorageengine.FileFooter)
    }

    // @@protoc_insertion_point(class_scope:kvstorageengine.FileFooter)
    private static final net.icircuit.bucketdb.models.proto.FileFooterProto.FileFooter DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new net.icircuit.bucketdb.models.proto.FileFooterProto.FileFooter();
    }

    public static net.icircuit.bucketdb.models.proto.FileFooterProto.FileFooter getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<FileFooter>
        PARSER = new com.google.protobuf.AbstractParser<FileFooter>() {
      @java.lang.Override
      public FileFooter parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new FileFooter(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<FileFooter> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<FileFooter> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public net.icircuit.bucketdb.models.proto.FileFooterProto.FileFooter getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_kvstorageengine_FileFooter_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_kvstorageengine_FileFooter_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025FileFooterProto.proto\022\017kvstorageengine" +
      "\"2\n\nFileFooter\022\021\n\tdibOffset\030\001 \001(\003\022\021\n\tdib" +
      "Length\030\002 \001(\003B5\n\"net.icircuit.bucketdb.mo" +
      "dels.protoB\017FileFooterProtob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_kvstorageengine_FileFooter_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_kvstorageengine_FileFooter_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_kvstorageengine_FileFooter_descriptor,
        new java.lang.String[] { "DibOffset", "DibLength", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
