// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RecordIndexBlockProto.proto

package net.icircuit.bucketdb.models.proto;

public final class RecordIndexBlockProto {
  private RecordIndexBlockProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface RecordIndexBlockOrBuilder extends
      // @@protoc_insertion_point(interface_extends:kvstorageengine.RecordIndexBlock)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .kvstorageengine.RecordIndexBlock.IndexRecord index = 1;</code>
     */
    java.util.List<net.icircuit.bucketdb.models.proto.RecordIndexBlockProto.RecordIndexBlock.IndexRecord> 
        getIndexList();
    /**
     * <code>repeated .kvstorageengine.RecordIndexBlock.IndexRecord index = 1;</code>
     */
    net.icircuit.bucketdb.models.proto.RecordIndexBlockProto.RecordIndexBlock.IndexRecord getIndex(int index);
    /**
     * <code>repeated .kvstorageengine.RecordIndexBlock.IndexRecord index = 1;</code>
     */
    int getIndexCount();
    /**
     * <code>repeated .kvstorageengine.RecordIndexBlock.IndexRecord index = 1;</code>
     */
    java.util.List<? extends net.icircuit.bucketdb.models.proto.RecordIndexBlockProto.RecordIndexBlock.IndexRecordOrBuilder> 
        getIndexOrBuilderList();
    /**
     * <code>repeated .kvstorageengine.RecordIndexBlock.IndexRecord index = 1;</code>
     */
    net.icircuit.bucketdb.models.proto.RecordIndexBlockProto.RecordIndexBlock.IndexRecordOrBuilder getIndexOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code kvstorageengine.RecordIndexBlock}
   */
  public  static final class RecordIndexBlock extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:kvstorageengine.RecordIndexBlock)
      RecordIndexBlockOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use RecordIndexBlock.newBuilder() to construct.
    private RecordIndexBlock(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private RecordIndexBlock() {
      index_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new RecordIndexBlock();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private RecordIndexBlock(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                index_ = new java.util.ArrayList<net.icircuit.bucketdb.models.proto.RecordIndexBlockProto.RecordIndexBlock.IndexRecord>();
                mutable_bitField0_ |= 0x00000001;
              }
              index_.add(
                  input.readMessage(net.icircuit.bucketdb.models.proto.RecordIndexBlockProto.RecordIndexBlock.IndexRecord.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          index_ = java.util.Collections.unmodifiableList(index_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return net.icircuit.bucketdb.models.proto.RecordIndexBlockProto.internal_static_kvstorageengine_RecordIndexBlock_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return net.icircuit.bucketdb.models.proto.RecordIndexBlockProto.internal_static_kvstorageengine_RecordIndexBlock_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              net.icircuit.bucketdb.models.proto.RecordIndexBlockProto.RecordIndexBlock.class, net.icircuit.bucketdb.models.proto.RecordIndexBlockProto.RecordIndexBlock.Builder.class);
    }

    public interface IndexRecordOrBuilder extends
        // @@protoc_insertion_point(interface_extends:kvstorageengine.RecordIndexBlock.IndexRecord)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>string rKey = 1;</code>
       * @return The rKey.
       */
      java.lang.String getRKey();
      /**
       * <code>string rKey = 1;</code>
       * @return The bytes for rKey.
       */
      com.google.protobuf.ByteString
          getRKeyBytes();

      /**
       * <code>int64 offset = 2;</code>
       * @return The offset.
       */
      long getOffset();

      /**
       * <code>int64 length = 3;</code>
       * @return The length.
       */
      long getLength();
    }
    /**
     * Protobuf type {@code kvstorageengine.RecordIndexBlock.IndexRecord}
     */
    public  static final class IndexRecord extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:kvstorageengine.RecordIndexBlock.IndexRecord)
        IndexRecordOrBuilder {
    private static final long serialVersionUID = 0L;
      // Use IndexRecord.newBuilder() to construct.
      private IndexRecord(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private IndexRecord() {
        rKey_ = "";
      }

      @java.lang.Override
      @SuppressWarnings({"unused"})
      protected java.lang.Object newInstance(
          UnusedPrivateParameter unused) {
        return new IndexRecord();
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      private IndexRecord(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                java.lang.String s = input.readStringRequireUtf8();

                rKey_ = s;
                break;
              }
              case 16: {

                offset_ = input.readInt64();
                break;
              }
              case 24: {

                length_ = input.readInt64();
                break;
              }
              default: {
                if (!parseUnknownField(
                    input, unknownFields, extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return net.icircuit.bucketdb.models.proto.RecordIndexBlockProto.internal_static_kvstorageengine_RecordIndexBlock_IndexRecord_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return net.icircuit.bucketdb.models.proto.RecordIndexBlockProto.internal_static_kvstorageengine_RecordIndexBlock_IndexRecord_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                net.icircuit.bucketdb.models.proto.RecordIndexBlockProto.RecordIndexBlock.IndexRecord.class, net.icircuit.bucketdb.models.proto.RecordIndexBlockProto.RecordIndexBlock.IndexRecord.Builder.class);
      }

      public static final int RKEY_FIELD_NUMBER = 1;
      private volatile java.lang.Object rKey_;
      /**
       * <code>string rKey = 1;</code>
       * @return The rKey.
       */
      public java.lang.String getRKey() {
        java.lang.Object ref = rKey_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          rKey_ = s;
          return s;
        }
      }
      /**
       * <code>string rKey = 1;</code>
       * @return The bytes for rKey.
       */
      public com.google.protobuf.ByteString
          getRKeyBytes() {
        java.lang.Object ref = rKey_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          rKey_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int OFFSET_FIELD_NUMBER = 2;
      private long offset_;
      /**
       * <code>int64 offset = 2;</code>
       * @return The offset.
       */
      public long getOffset() {
        return offset_;
      }

      public static final int LENGTH_FIELD_NUMBER = 3;
      private long length_;
      /**
       * <code>int64 length = 3;</code>
       * @return The length.
       */
      public long getLength() {
        return length_;
      }

      private byte memoizedIsInitialized = -1;
      @java.lang.Override
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      @java.lang.Override
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (!getRKeyBytes().isEmpty()) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 1, rKey_);
        }
        if (offset_ != 0L) {
          output.writeInt64(2, offset_);
        }
        if (length_ != 0L) {
          output.writeInt64(3, length_);
        }
        unknownFields.writeTo(output);
      }

      @java.lang.Override
      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (!getRKeyBytes().isEmpty()) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, rKey_);
        }
        if (offset_ != 0L) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt64Size(2, offset_);
        }
        if (length_ != 0L) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt64Size(3, length_);
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
      }

      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof net.icircuit.bucketdb.models.proto.RecordIndexBlockProto.RecordIndexBlock.IndexRecord)) {
          return super.equals(obj);
        }
        net.icircuit.bucketdb.models.proto.RecordIndexBlockProto.RecordIndexBlock.IndexRecord other = (net.icircuit.bucketdb.models.proto.RecordIndexBlockProto.RecordIndexBlock.IndexRecord) obj;

        if (!getRKey()
            .equals(other.getRKey())) return false;
        if (getOffset()
            != other.getOffset()) return false;
        if (getLength()
            != other.getLength()) return false;
        if (!unknownFields.equals(other.unknownFields)) return false;
        return true;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + RKEY_FIELD_NUMBER;
        hash = (53 * hash) + getRKey().hashCode();
        hash = (37 * hash) + OFFSET_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getOffset());
        hash = (37 * hash) + LENGTH_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getLength());
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static net.icircuit.bucketdb.models.proto.RecordIndexBlockProto.RecordIndexBlock.IndexRecord parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static net.icircuit.bucketdb.models.proto.RecordIndexBlockProto.RecordIndexBlock.IndexRecord parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static net.icircuit.bucketdb.models.proto.RecordIndexBlockProto.RecordIndexBlock.IndexRecord parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static net.icircuit.bucketdb.models.proto.RecordIndexBlockProto.RecordIndexBlock.IndexRecord parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static net.icircuit.bucketdb.models.proto.RecordIndexBlockProto.RecordIndexBlock.IndexRecord parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static net.icircuit.bucketdb.models.proto.RecordIndexBlockProto.RecordIndexBlock.IndexRecord parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static net.icircuit.bucketdb.models.proto.RecordIndexBlockProto.RecordIndexBlock.IndexRecord parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static net.icircuit.bucketdb.models.proto.RecordIndexBlockProto.RecordIndexBlock.IndexRecord parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static net.icircuit.bucketdb.models.proto.RecordIndexBlockProto.RecordIndexBlock.IndexRecord parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static net.icircuit.bucketdb.models.proto.RecordIndexBlockProto.RecordIndexBlock.IndexRecord parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static net.icircuit.bucketdb.models.proto.RecordIndexBlockProto.RecordIndexBlock.IndexRecord parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static net.icircuit.bucketdb.models.proto.RecordIndexBlockProto.RecordIndexBlock.IndexRecord parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      @java.lang.Override
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(net.icircuit.bucketdb.models.proto.RecordIndexBlockProto.RecordIndexBlock.IndexRecord prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      @java.lang.Override
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code kvstorageengine.RecordIndexBlock.IndexRecord}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:kvstorageengine.RecordIndexBlock.IndexRecord)
          net.icircuit.bucketdb.models.proto.RecordIndexBlockProto.RecordIndexBlock.IndexRecordOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return net.icircuit.bucketdb.models.proto.RecordIndexBlockProto.internal_static_kvstorageengine_RecordIndexBlock_IndexRecord_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return net.icircuit.bucketdb.models.proto.RecordIndexBlockProto.internal_static_kvstorageengine_RecordIndexBlock_IndexRecord_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  net.icircuit.bucketdb.models.proto.RecordIndexBlockProto.RecordIndexBlock.IndexRecord.class, net.icircuit.bucketdb.models.proto.RecordIndexBlockProto.RecordIndexBlock.IndexRecord.Builder.class);
        }

        // Construct using net.icircuit.bucketdb.models.proto.RecordIndexBlockProto.RecordIndexBlock.IndexRecord.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
          }
        }
        @java.lang.Override
        public Builder clear() {
          super.clear();
          rKey_ = "";

          offset_ = 0L;

          length_ = 0L;

          return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return net.icircuit.bucketdb.models.proto.RecordIndexBlockProto.internal_static_kvstorageengine_RecordIndexBlock_IndexRecord_descriptor;
        }

        @java.lang.Override
        public net.icircuit.bucketdb.models.proto.RecordIndexBlockProto.RecordIndexBlock.IndexRecord getDefaultInstanceForType() {
          return net.icircuit.bucketdb.models.proto.RecordIndexBlockProto.RecordIndexBlock.IndexRecord.getDefaultInstance();
        }

        @java.lang.Override
        public net.icircuit.bucketdb.models.proto.RecordIndexBlockProto.RecordIndexBlock.IndexRecord build() {
          net.icircuit.bucketdb.models.proto.RecordIndexBlockProto.RecordIndexBlock.IndexRecord result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        @java.lang.Override
        public net.icircuit.bucketdb.models.proto.RecordIndexBlockProto.RecordIndexBlock.IndexRecord buildPartial() {
          net.icircuit.bucketdb.models.proto.RecordIndexBlockProto.RecordIndexBlock.IndexRecord result = new net.icircuit.bucketdb.models.proto.RecordIndexBlockProto.RecordIndexBlock.IndexRecord(this);
          result.rKey_ = rKey_;
          result.offset_ = offset_;
          result.length_ = length_;
          onBuilt();
          return result;
        }

        @java.lang.Override
        public Builder clone() {
          return super.clone();
        }
        @java.lang.Override
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.setField(field, value);
        }
        @java.lang.Override
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return super.clearField(field);
        }
        @java.lang.Override
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return super.clearOneof(oneof);
        }
        @java.lang.Override
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, java.lang.Object value) {
          return super.setRepeatedField(field, index, value);
        }
        @java.lang.Override
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.addRepeatedField(field, value);
        }
        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof net.icircuit.bucketdb.models.proto.RecordIndexBlockProto.RecordIndexBlock.IndexRecord) {
            return mergeFrom((net.icircuit.bucketdb.models.proto.RecordIndexBlockProto.RecordIndexBlock.IndexRecord)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(net.icircuit.bucketdb.models.proto.RecordIndexBlockProto.RecordIndexBlock.IndexRecord other) {
          if (other == net.icircuit.bucketdb.models.proto.RecordIndexBlockProto.RecordIndexBlock.IndexRecord.getDefaultInstance()) return this;
          if (!other.getRKey().isEmpty()) {
            rKey_ = other.rKey_;
            onChanged();
          }
          if (other.getOffset() != 0L) {
            setOffset(other.getOffset());
          }
          if (other.getLength() != 0L) {
            setLength(other.getLength());
          }
          this.mergeUnknownFields(other.unknownFields);
          onChanged();
          return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
          return true;
        }

        @java.lang.Override
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          net.icircuit.bucketdb.models.proto.RecordIndexBlockProto.RecordIndexBlock.IndexRecord parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (net.icircuit.bucketdb.models.proto.RecordIndexBlockProto.RecordIndexBlock.IndexRecord) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }

        private java.lang.Object rKey_ = "";
        /**
         * <code>string rKey = 1;</code>
         * @return The rKey.
         */
        public java.lang.String getRKey() {
          java.lang.Object ref = rKey_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            rKey_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>string rKey = 1;</code>
         * @return The bytes for rKey.
         */
        public com.google.protobuf.ByteString
            getRKeyBytes() {
          java.lang.Object ref = rKey_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            rKey_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>string rKey = 1;</code>
         * @param value The rKey to set.
         * @return This builder for chaining.
         */
        public Builder setRKey(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          rKey_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>string rKey = 1;</code>
         * @return This builder for chaining.
         */
        public Builder clearRKey() {
          
          rKey_ = getDefaultInstance().getRKey();
          onChanged();
          return this;
        }
        /**
         * <code>string rKey = 1;</code>
         * @param value The bytes for rKey to set.
         * @return This builder for chaining.
         */
        public Builder setRKeyBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
          
          rKey_ = value;
          onChanged();
          return this;
        }

        private long offset_ ;
        /**
         * <code>int64 offset = 2;</code>
         * @return The offset.
         */
        public long getOffset() {
          return offset_;
        }
        /**
         * <code>int64 offset = 2;</code>
         * @param value The offset to set.
         * @return This builder for chaining.
         */
        public Builder setOffset(long value) {
          
          offset_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>int64 offset = 2;</code>
         * @return This builder for chaining.
         */
        public Builder clearOffset() {
          
          offset_ = 0L;
          onChanged();
          return this;
        }

        private long length_ ;
        /**
         * <code>int64 length = 3;</code>
         * @return The length.
         */
        public long getLength() {
          return length_;
        }
        /**
         * <code>int64 length = 3;</code>
         * @param value The length to set.
         * @return This builder for chaining.
         */
        public Builder setLength(long value) {
          
          length_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>int64 length = 3;</code>
         * @return This builder for chaining.
         */
        public Builder clearLength() {
          
          length_ = 0L;
          onChanged();
          return this;
        }
        @java.lang.Override
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFields(unknownFields);
        }

        @java.lang.Override
        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:kvstorageengine.RecordIndexBlock.IndexRecord)
      }

      // @@protoc_insertion_point(class_scope:kvstorageengine.RecordIndexBlock.IndexRecord)
      private static final net.icircuit.bucketdb.models.proto.RecordIndexBlockProto.RecordIndexBlock.IndexRecord DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new net.icircuit.bucketdb.models.proto.RecordIndexBlockProto.RecordIndexBlock.IndexRecord();
      }

      public static net.icircuit.bucketdb.models.proto.RecordIndexBlockProto.RecordIndexBlock.IndexRecord getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static final com.google.protobuf.Parser<IndexRecord>
          PARSER = new com.google.protobuf.AbstractParser<IndexRecord>() {
        @java.lang.Override
        public IndexRecord parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new IndexRecord(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<IndexRecord> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<IndexRecord> getParserForType() {
        return PARSER;
      }

      @java.lang.Override
      public net.icircuit.bucketdb.models.proto.RecordIndexBlockProto.RecordIndexBlock.IndexRecord getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    public static final int INDEX_FIELD_NUMBER = 1;
    private java.util.List<net.icircuit.bucketdb.models.proto.RecordIndexBlockProto.RecordIndexBlock.IndexRecord> index_;
    /**
     * <code>repeated .kvstorageengine.RecordIndexBlock.IndexRecord index = 1;</code>
     */
    public java.util.List<net.icircuit.bucketdb.models.proto.RecordIndexBlockProto.RecordIndexBlock.IndexRecord> getIndexList() {
      return index_;
    }
    /**
     * <code>repeated .kvstorageengine.RecordIndexBlock.IndexRecord index = 1;</code>
     */
    public java.util.List<? extends net.icircuit.bucketdb.models.proto.RecordIndexBlockProto.RecordIndexBlock.IndexRecordOrBuilder> 
        getIndexOrBuilderList() {
      return index_;
    }
    /**
     * <code>repeated .kvstorageengine.RecordIndexBlock.IndexRecord index = 1;</code>
     */
    public int getIndexCount() {
      return index_.size();
    }
    /**
     * <code>repeated .kvstorageengine.RecordIndexBlock.IndexRecord index = 1;</code>
     */
    public net.icircuit.bucketdb.models.proto.RecordIndexBlockProto.RecordIndexBlock.IndexRecord getIndex(int index) {
      return index_.get(index);
    }
    /**
     * <code>repeated .kvstorageengine.RecordIndexBlock.IndexRecord index = 1;</code>
     */
    public net.icircuit.bucketdb.models.proto.RecordIndexBlockProto.RecordIndexBlock.IndexRecordOrBuilder getIndexOrBuilder(
        int index) {
      return index_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < index_.size(); i++) {
        output.writeMessage(1, index_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < index_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, index_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof net.icircuit.bucketdb.models.proto.RecordIndexBlockProto.RecordIndexBlock)) {
        return super.equals(obj);
      }
      net.icircuit.bucketdb.models.proto.RecordIndexBlockProto.RecordIndexBlock other = (net.icircuit.bucketdb.models.proto.RecordIndexBlockProto.RecordIndexBlock) obj;

      if (!getIndexList()
          .equals(other.getIndexList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getIndexCount() > 0) {
        hash = (37 * hash) + INDEX_FIELD_NUMBER;
        hash = (53 * hash) + getIndexList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static net.icircuit.bucketdb.models.proto.RecordIndexBlockProto.RecordIndexBlock parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.icircuit.bucketdb.models.proto.RecordIndexBlockProto.RecordIndexBlock parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.icircuit.bucketdb.models.proto.RecordIndexBlockProto.RecordIndexBlock parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.icircuit.bucketdb.models.proto.RecordIndexBlockProto.RecordIndexBlock parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.icircuit.bucketdb.models.proto.RecordIndexBlockProto.RecordIndexBlock parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.icircuit.bucketdb.models.proto.RecordIndexBlockProto.RecordIndexBlock parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.icircuit.bucketdb.models.proto.RecordIndexBlockProto.RecordIndexBlock parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static net.icircuit.bucketdb.models.proto.RecordIndexBlockProto.RecordIndexBlock parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static net.icircuit.bucketdb.models.proto.RecordIndexBlockProto.RecordIndexBlock parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static net.icircuit.bucketdb.models.proto.RecordIndexBlockProto.RecordIndexBlock parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static net.icircuit.bucketdb.models.proto.RecordIndexBlockProto.RecordIndexBlock parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static net.icircuit.bucketdb.models.proto.RecordIndexBlockProto.RecordIndexBlock parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(net.icircuit.bucketdb.models.proto.RecordIndexBlockProto.RecordIndexBlock prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code kvstorageengine.RecordIndexBlock}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:kvstorageengine.RecordIndexBlock)
        net.icircuit.bucketdb.models.proto.RecordIndexBlockProto.RecordIndexBlockOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return net.icircuit.bucketdb.models.proto.RecordIndexBlockProto.internal_static_kvstorageengine_RecordIndexBlock_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return net.icircuit.bucketdb.models.proto.RecordIndexBlockProto.internal_static_kvstorageengine_RecordIndexBlock_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                net.icircuit.bucketdb.models.proto.RecordIndexBlockProto.RecordIndexBlock.class, net.icircuit.bucketdb.models.proto.RecordIndexBlockProto.RecordIndexBlock.Builder.class);
      }

      // Construct using net.icircuit.bucketdb.models.proto.RecordIndexBlockProto.RecordIndexBlock.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getIndexFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (indexBuilder_ == null) {
          index_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          indexBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return net.icircuit.bucketdb.models.proto.RecordIndexBlockProto.internal_static_kvstorageengine_RecordIndexBlock_descriptor;
      }

      @java.lang.Override
      public net.icircuit.bucketdb.models.proto.RecordIndexBlockProto.RecordIndexBlock getDefaultInstanceForType() {
        return net.icircuit.bucketdb.models.proto.RecordIndexBlockProto.RecordIndexBlock.getDefaultInstance();
      }

      @java.lang.Override
      public net.icircuit.bucketdb.models.proto.RecordIndexBlockProto.RecordIndexBlock build() {
        net.icircuit.bucketdb.models.proto.RecordIndexBlockProto.RecordIndexBlock result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public net.icircuit.bucketdb.models.proto.RecordIndexBlockProto.RecordIndexBlock buildPartial() {
        net.icircuit.bucketdb.models.proto.RecordIndexBlockProto.RecordIndexBlock result = new net.icircuit.bucketdb.models.proto.RecordIndexBlockProto.RecordIndexBlock(this);
        int from_bitField0_ = bitField0_;
        if (indexBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            index_ = java.util.Collections.unmodifiableList(index_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.index_ = index_;
        } else {
          result.index_ = indexBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof net.icircuit.bucketdb.models.proto.RecordIndexBlockProto.RecordIndexBlock) {
          return mergeFrom((net.icircuit.bucketdb.models.proto.RecordIndexBlockProto.RecordIndexBlock)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(net.icircuit.bucketdb.models.proto.RecordIndexBlockProto.RecordIndexBlock other) {
        if (other == net.icircuit.bucketdb.models.proto.RecordIndexBlockProto.RecordIndexBlock.getDefaultInstance()) return this;
        if (indexBuilder_ == null) {
          if (!other.index_.isEmpty()) {
            if (index_.isEmpty()) {
              index_ = other.index_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureIndexIsMutable();
              index_.addAll(other.index_);
            }
            onChanged();
          }
        } else {
          if (!other.index_.isEmpty()) {
            if (indexBuilder_.isEmpty()) {
              indexBuilder_.dispose();
              indexBuilder_ = null;
              index_ = other.index_;
              bitField0_ = (bitField0_ & ~0x00000001);
              indexBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getIndexFieldBuilder() : null;
            } else {
              indexBuilder_.addAllMessages(other.index_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        net.icircuit.bucketdb.models.proto.RecordIndexBlockProto.RecordIndexBlock parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (net.icircuit.bucketdb.models.proto.RecordIndexBlockProto.RecordIndexBlock) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<net.icircuit.bucketdb.models.proto.RecordIndexBlockProto.RecordIndexBlock.IndexRecord> index_ =
        java.util.Collections.emptyList();
      private void ensureIndexIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          index_ = new java.util.ArrayList<net.icircuit.bucketdb.models.proto.RecordIndexBlockProto.RecordIndexBlock.IndexRecord>(index_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          net.icircuit.bucketdb.models.proto.RecordIndexBlockProto.RecordIndexBlock.IndexRecord, net.icircuit.bucketdb.models.proto.RecordIndexBlockProto.RecordIndexBlock.IndexRecord.Builder, net.icircuit.bucketdb.models.proto.RecordIndexBlockProto.RecordIndexBlock.IndexRecordOrBuilder> indexBuilder_;

      /**
       * <code>repeated .kvstorageengine.RecordIndexBlock.IndexRecord index = 1;</code>
       */
      public java.util.List<net.icircuit.bucketdb.models.proto.RecordIndexBlockProto.RecordIndexBlock.IndexRecord> getIndexList() {
        if (indexBuilder_ == null) {
          return java.util.Collections.unmodifiableList(index_);
        } else {
          return indexBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .kvstorageengine.RecordIndexBlock.IndexRecord index = 1;</code>
       */
      public int getIndexCount() {
        if (indexBuilder_ == null) {
          return index_.size();
        } else {
          return indexBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .kvstorageengine.RecordIndexBlock.IndexRecord index = 1;</code>
       */
      public net.icircuit.bucketdb.models.proto.RecordIndexBlockProto.RecordIndexBlock.IndexRecord getIndex(int index) {
        if (indexBuilder_ == null) {
          return index_.get(index);
        } else {
          return indexBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .kvstorageengine.RecordIndexBlock.IndexRecord index = 1;</code>
       */
      public Builder setIndex(
          int index, net.icircuit.bucketdb.models.proto.RecordIndexBlockProto.RecordIndexBlock.IndexRecord value) {
        if (indexBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureIndexIsMutable();
          index_.set(index, value);
          onChanged();
        } else {
          indexBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .kvstorageengine.RecordIndexBlock.IndexRecord index = 1;</code>
       */
      public Builder setIndex(
          int index, net.icircuit.bucketdb.models.proto.RecordIndexBlockProto.RecordIndexBlock.IndexRecord.Builder builderForValue) {
        if (indexBuilder_ == null) {
          ensureIndexIsMutable();
          index_.set(index, builderForValue.build());
          onChanged();
        } else {
          indexBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .kvstorageengine.RecordIndexBlock.IndexRecord index = 1;</code>
       */
      public Builder addIndex(net.icircuit.bucketdb.models.proto.RecordIndexBlockProto.RecordIndexBlock.IndexRecord value) {
        if (indexBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureIndexIsMutable();
          index_.add(value);
          onChanged();
        } else {
          indexBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .kvstorageengine.RecordIndexBlock.IndexRecord index = 1;</code>
       */
      public Builder addIndex(
          int index, net.icircuit.bucketdb.models.proto.RecordIndexBlockProto.RecordIndexBlock.IndexRecord value) {
        if (indexBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureIndexIsMutable();
          index_.add(index, value);
          onChanged();
        } else {
          indexBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .kvstorageengine.RecordIndexBlock.IndexRecord index = 1;</code>
       */
      public Builder addIndex(
          net.icircuit.bucketdb.models.proto.RecordIndexBlockProto.RecordIndexBlock.IndexRecord.Builder builderForValue) {
        if (indexBuilder_ == null) {
          ensureIndexIsMutable();
          index_.add(builderForValue.build());
          onChanged();
        } else {
          indexBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .kvstorageengine.RecordIndexBlock.IndexRecord index = 1;</code>
       */
      public Builder addIndex(
          int index, net.icircuit.bucketdb.models.proto.RecordIndexBlockProto.RecordIndexBlock.IndexRecord.Builder builderForValue) {
        if (indexBuilder_ == null) {
          ensureIndexIsMutable();
          index_.add(index, builderForValue.build());
          onChanged();
        } else {
          indexBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .kvstorageengine.RecordIndexBlock.IndexRecord index = 1;</code>
       */
      public Builder addAllIndex(
          java.lang.Iterable<? extends net.icircuit.bucketdb.models.proto.RecordIndexBlockProto.RecordIndexBlock.IndexRecord> values) {
        if (indexBuilder_ == null) {
          ensureIndexIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, index_);
          onChanged();
        } else {
          indexBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .kvstorageengine.RecordIndexBlock.IndexRecord index = 1;</code>
       */
      public Builder clearIndex() {
        if (indexBuilder_ == null) {
          index_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          indexBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .kvstorageengine.RecordIndexBlock.IndexRecord index = 1;</code>
       */
      public Builder removeIndex(int index) {
        if (indexBuilder_ == null) {
          ensureIndexIsMutable();
          index_.remove(index);
          onChanged();
        } else {
          indexBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .kvstorageengine.RecordIndexBlock.IndexRecord index = 1;</code>
       */
      public net.icircuit.bucketdb.models.proto.RecordIndexBlockProto.RecordIndexBlock.IndexRecord.Builder getIndexBuilder(
          int index) {
        return getIndexFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .kvstorageengine.RecordIndexBlock.IndexRecord index = 1;</code>
       */
      public net.icircuit.bucketdb.models.proto.RecordIndexBlockProto.RecordIndexBlock.IndexRecordOrBuilder getIndexOrBuilder(
          int index) {
        if (indexBuilder_ == null) {
          return index_.get(index);  } else {
          return indexBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .kvstorageengine.RecordIndexBlock.IndexRecord index = 1;</code>
       */
      public java.util.List<? extends net.icircuit.bucketdb.models.proto.RecordIndexBlockProto.RecordIndexBlock.IndexRecordOrBuilder> 
           getIndexOrBuilderList() {
        if (indexBuilder_ != null) {
          return indexBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(index_);
        }
      }
      /**
       * <code>repeated .kvstorageengine.RecordIndexBlock.IndexRecord index = 1;</code>
       */
      public net.icircuit.bucketdb.models.proto.RecordIndexBlockProto.RecordIndexBlock.IndexRecord.Builder addIndexBuilder() {
        return getIndexFieldBuilder().addBuilder(
            net.icircuit.bucketdb.models.proto.RecordIndexBlockProto.RecordIndexBlock.IndexRecord.getDefaultInstance());
      }
      /**
       * <code>repeated .kvstorageengine.RecordIndexBlock.IndexRecord index = 1;</code>
       */
      public net.icircuit.bucketdb.models.proto.RecordIndexBlockProto.RecordIndexBlock.IndexRecord.Builder addIndexBuilder(
          int index) {
        return getIndexFieldBuilder().addBuilder(
            index, net.icircuit.bucketdb.models.proto.RecordIndexBlockProto.RecordIndexBlock.IndexRecord.getDefaultInstance());
      }
      /**
       * <code>repeated .kvstorageengine.RecordIndexBlock.IndexRecord index = 1;</code>
       */
      public java.util.List<net.icircuit.bucketdb.models.proto.RecordIndexBlockProto.RecordIndexBlock.IndexRecord.Builder> 
           getIndexBuilderList() {
        return getIndexFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          net.icircuit.bucketdb.models.proto.RecordIndexBlockProto.RecordIndexBlock.IndexRecord, net.icircuit.bucketdb.models.proto.RecordIndexBlockProto.RecordIndexBlock.IndexRecord.Builder, net.icircuit.bucketdb.models.proto.RecordIndexBlockProto.RecordIndexBlock.IndexRecordOrBuilder> 
          getIndexFieldBuilder() {
        if (indexBuilder_ == null) {
          indexBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              net.icircuit.bucketdb.models.proto.RecordIndexBlockProto.RecordIndexBlock.IndexRecord, net.icircuit.bucketdb.models.proto.RecordIndexBlockProto.RecordIndexBlock.IndexRecord.Builder, net.icircuit.bucketdb.models.proto.RecordIndexBlockProto.RecordIndexBlock.IndexRecordOrBuilder>(
                  index_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          index_ = null;
        }
        return indexBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:kvstorageengine.RecordIndexBlock)
    }

    // @@protoc_insertion_point(class_scope:kvstorageengine.RecordIndexBlock)
    private static final net.icircuit.bucketdb.models.proto.RecordIndexBlockProto.RecordIndexBlock DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new net.icircuit.bucketdb.models.proto.RecordIndexBlockProto.RecordIndexBlock();
    }

    public static net.icircuit.bucketdb.models.proto.RecordIndexBlockProto.RecordIndexBlock getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<RecordIndexBlock>
        PARSER = new com.google.protobuf.AbstractParser<RecordIndexBlock>() {
      @java.lang.Override
      public RecordIndexBlock parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new RecordIndexBlock(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<RecordIndexBlock> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<RecordIndexBlock> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public net.icircuit.bucketdb.models.proto.RecordIndexBlockProto.RecordIndexBlock getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_kvstorageengine_RecordIndexBlock_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_kvstorageengine_RecordIndexBlock_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_kvstorageengine_RecordIndexBlock_IndexRecord_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_kvstorageengine_RecordIndexBlock_IndexRecord_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\033RecordIndexBlockProto.proto\022\017kvstorage" +
      "engine\"\215\001\n\020RecordIndexBlock\022<\n\005index\030\001 \003" +
      "(\0132-.kvstorageengine.RecordIndexBlock.In" +
      "dexRecord\032;\n\013IndexRecord\022\014\n\004rKey\030\001 \001(\t\022\016" +
      "\n\006offset\030\002 \001(\003\022\016\n\006length\030\003 \001(\003B;\n\"net.ic" +
      "ircuit.bucketdb.models.protoB\025RecordInde" +
      "xBlockProtob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_kvstorageengine_RecordIndexBlock_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_kvstorageengine_RecordIndexBlock_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_kvstorageengine_RecordIndexBlock_descriptor,
        new java.lang.String[] { "Index", });
    internal_static_kvstorageengine_RecordIndexBlock_IndexRecord_descriptor =
      internal_static_kvstorageengine_RecordIndexBlock_descriptor.getNestedTypes().get(0);
    internal_static_kvstorageengine_RecordIndexBlock_IndexRecord_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_kvstorageengine_RecordIndexBlock_IndexRecord_descriptor,
        new java.lang.String[] { "RKey", "Offset", "Length", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
